config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用のパス
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update] do
      # ユーザーの投稿一覧ページのルーティング
      get 'posts'
    end
    resources :tags, except: [:new, :show]
    resources :posts, only: [:show, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy]
  end

   scope module: :public do
    root to:  'homes#top'
    # 退会確認画面のルーティング
    get  '/users/check' => 'users#check'
    # 論理削除のルーティング
    patch  '/users/withdraw' => 'users#withdraw'
    # 通知機能のルーティング
    resources :notifications, only: [:index, :destroy]
    # 通報完了画面のルーティング
    get 'reports/completed' => 'reports#completed', as: 'completed'
    resources :posts do
      collection do
      # タグ検索のルーティング
      get 'search_tag'
      get 'search'
      end
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :users, except: [:new, :destroy] do
      member do
        # いいねした投稿を取得するため投稿idを付与
        get :likes
        # 下書き一覧ページのルーティング
        get :draft
      end
      # ユーザーを通報するためのルーティング
      resources :reports, only: [:new, :create]
      resource :relationships, only: [:create, :destroy]
      # フォローしてるユーザーを取得するためのルーティング
      get 'followings' => 'relationships#followings', as: 'followings'
      # フォロワーを取得するためのルーティング
    	get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags,dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tag = Tag.new
    @tags = Tag.all.page(params[:page]).per(10).order(created_at: :desc)
  end

  def create
      @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "タグの登録に成功しました。"
    else
      @tags = Tag.all.page(params[:page]).per(10).order(created_at: :desc)
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
     @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: "タグの編集に成功しました。"
    else
      render :edit
    end
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグの削除に成功しました。"
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-12  mx-md-auto mt-5">
      <h1 class="responsive-title text-center">タグを編集</h1>
      <%= form_with model: @tag, url: admin_tag_path, method: :patch do |f| %>
      <!--エラーメッセージ-->
      <div class="row justify-content-center text-center mr-4"><%= render 'layouts/errors', obj: @tag %></div>
        <div class="row mt-5">
          <%= f.label :name, "タグ名", class: "col-form-label col-3" %>
          <%= f.text_field :name, class: "form-control col-md-9 col-8"%>
        </div>
        <div class="row d-flex justify-content-center mt-5">
          <%= f.submit "変更を保存する", class: "btn btn-success"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-12">
      <h1 class="responsive-title text-center">タグ一覧</h1>
      <%= render 'layouts/errors', obj: @tag %>
      <div class="mt-5">
      <%= form_with model: @tag, url: admin_tags_path do |f| %>
        <div class="row justify-content-center">
          <%= f.label :name, "タグ追加", class: "col-form-label col-md-2 col-4" %>
          <%= f.text_field :name, class: "form-control col-md-6 col-5" %>
          <%= f.submit "追加", class: "btn btn-success col-2 ml-md-2 ml-1"%>
        </div>
      <% end %>
    </div>
      <table class="table table-borderless text-center mt-5">
        <% @tags.each do |tag| %>
          <tr>
            <td><%= tag.name %></td>
            <td><%= link_to "タグを編集", edit_admin_tag_path(tag), class: "btn btn-success" %></td>
            <td><%= link_to "削除", admin_tag_path(tag), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除しますか？"}  %></td>
          </tr>
        <% end %>
      </table>
      <div class="d-flex justify-content-center mt-5"><%= paginate @tags %></div>
    </div>
  </div>
</div>