config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用のパス
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update] do
      # ユーザーの投稿一覧ページのルーティング
      get 'posts'
    end
    resources :tags, except: [:new, :show]
    resources :posts, only: [:show, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy]
  end

   scope module: :public do
    root to:  'homes#top'
    # 退会確認画面のルーティング
    get  '/users/check' => 'users#check'
    # 論理削除のルーティング
    patch  '/users/withdraw' => 'users#withdraw'
    # 通知機能のルーティング
    resources :notifications, only: [:index, :destroy]
    # 通報完了画面のルーティング
    get 'reports/completed' => 'reports#completed', as: 'completed'
    resources :posts do
      collection do
      # タグ検索のルーティング
      get 'search_tag'
      get 'search'
      end
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :users, except: [:new, :destroy] do
      member do
        # いいねした投稿を取得するため投稿idを付与
        get :likes
        # 下書き一覧ページのルーティング
        get :draft
      end
      # ユーザーを通報するためのルーティング
      resources :reports, only: [:new, :create]
      resource :relationships, only: [:create, :destroy]
      # フォローしてるユーザーを取得するためのルーティング
      get 'followings' => 'relationships#followings', as: 'followings'
      # フォロワーを取得するためのルーティング
    	get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"
  
  validates :reason, presence: true

  enum status: { waiting: 0, keep: 1, finished: 2 }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController

  def index
    @reports = Report.all.page(params[:page]).per(15).order(created_at: :desc)
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to admin_reports_path, notice: "通報ステータスの変更に成功しました。"
    else
      render :show
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to admin_reports_path, notice: "通報の削除に成功しました。"
  end

  private
  def report_params
    params.require(:report).permit(:status)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="responsive-title text-center">通報一覧</h1>
      <table class="table text-center mt-5">
        <thead>
          <tr>
            <th>通報ID</th>
            <th>ユーザーネーム</th>
            <th>通報者</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @reports.each do |report| %>
            <tr>
              <td><%= link_to report.id, admin_report_path(report) %></td>
              <td><%= report.reported.name %></td>
              <td><%= report.reporter.name %></td>
              <td>
                <% if report.status == "waiting" %>
                 <p class="text-danger"><%= report.status_i18n %></p>
                <% elsif report.status == "keep" %>
                 <p class="text-dark"><%= report.status_i18n %></p>
                <% else %>
                 <p class="text-success"><%= report.status_i18n %></p>
                <% end %>
              </td>
              <td>
                <% if report.status == "finished" %>
                  <%= link_to "削除", admin_report_path(report), method: :delete, class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center mt-5"><%= paginate @reports %></div>
    </div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 mx-auto">
      <h1 class="responsive-title text-center">通報詳細</h1>
      <table class="table table-borderless text-center mt-5">
          <tbody>
            <tr>
              <th>通報ID</th>
              <td><%= @report.id %></td>
            </tr>
            <tr>
              <th>ユーザーネーム</th>
              <td><span class="mr-5"><%= link_to @report.reported.name, admin_user_path(@report.reported) %></span><span><%= link_to "投稿一覧", admin_user_posts_path(@report.reported)%></span></td>
            </tr>
            <tr>
              <th>通報者</th>
              <td><%= link_to @report.reporter.name, admin_user_path(@report.reporter) %></td>
            </tr>
            <tr>
              <th>理由</th>
              <td class="border"><%= @report.reason %></td>
            </tr>
            <tr>
              <th>対応ステータス</th>
              <td>
                <%= form_with model:@report, url:admin_report_path(@report), method: :patch, local: true do |f| %>
                  <%= f.select :status, Report.statuses.keys.map { |k| [t("enums.report.status.#{k}"), k] } %>
                  <%= f.submit '更新' %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>