config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用のパス
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update] do
      # ユーザーの投稿一覧ページのルーティング
      get 'posts'
    end
    resources :tags, except: [:new, :show]
    resources :posts, only: [:show, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy]
  end

   scope module: :public do
    root to:  'homes#top'
    # 退会確認画面のルーティング
    get  '/users/check' => 'users#check'
    # 論理削除のルーティング
    patch  '/users/withdraw' => 'users#withdraw'
    # 通知機能のルーティング
    resources :notifications, only: [:index, :destroy]
    # 通報完了画面のルーティング
    get 'reports/completed' => 'reports#completed', as: 'completed'
    resources :posts do
      collection do
      # タグ検索のルーティング
      get 'search_tag'
      get 'search'
      end
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :users, except: [:new, :destroy] do
      member do
        # いいねした投稿を取得するため投稿idを付与
        get :likes
        # 下書き一覧ページのルーティング
        get :draft
      end
      # ユーザーを通報するためのルーティング
      resources :reports, only: [:new, :create]
      resource :relationships, only: [:create, :destroy]
      # フォローしてるユーザーを取得するためのルーティング
      get 'followings' => 'relationships#followings', as: 'followings'
      # フォロワーを取得するためのルーティング
    	get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  has_many :notifications, dependent: :destroy
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 150 }
  
  # プロフィール画像がなければ'no_image.jpg'を設定
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  # フォローしているかの判別
  def following?(user)
    followings.include?(user)
  end
  
  # ユーザー検索メソッド
  def self.search(word)
      @user = User.where("name LIKE?","%#{word}%")
  end
  
  # ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:word]
      @users = User.search(params[:word]).page(params[:page]).per(15)
    else
      @users = User.all.page(params[:page]).per(15)
    end
  end

  def posts
    @user = User.find(params[:user_id])
    @posts = @user.posts.where(displayed: true).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー情報の編集に成功しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_search.html.erb
<!--ユーザー検索フォーム-->
<%= form_with url: admin_users_path, local: true, method: :get do |form| %>
  <%= form.text_field :word %>
  <%= form.submit '検索' %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-11">
      <h1 class="responsive-title text-center">プロフィール編集</h1>
      <% if @user.email == 'guest@example.com'%>
        <h5 class="text-center mt-5">ゲストユーザーのプロフィールの編集はできません。</h5>
      <% else %>
        <%= form_with model: @user, url: admin_user_path do |f| %>
        <!--エラーメッセージ-->
          <div class="row justify-content-center text-center mr-4"><%= render 'layouts/errors', obj: @user %></div>
          <div class="row mt-5">
            <%= f.label :画像, class: "col-form-label col-sm-3 text-center"%>
            <!--画像プレビュー機能-->
            <%= image_tag @user.get_profile_image, onClick: "$('.user_img_field').click()", class: "user_img_prev rounded-circle col-sm-4 col-8 mx-auto ml-md-3", size: "180x180" %>
            <%= f.file_field :profile_image, class: "user_img_field ml-5 mt-5", style: 'display:none;', accept: 'image/*' %>
          </div>
          <div class="row mt-5">
            <%= f.label :ユーザーネーム, class: "col-form-label col-sm-3 text-center"%>
            <%= f.text_field :name, class: "form-control col-sm-9"%>
          </div>
          <div class="row mt-5">
            <%= f.label :自己紹介, class: "col-form-label col-sm-3 text-center"%>
            <%= f.text_area :introduction, class: "form-control col-sm-9",placeholder: "150文字まで", size: "30x5"%>
          </div>
          <div class="row mt-5">
            <%= f.label :ステータス, class: "col-form-label col-sm-3 text-center"%>
            <div class="col-sm-9 d-flex">
              <div class="form-check form-check-inline col-3 offset-2">
                <%= f.radio_button :is_deleted, :false, class: "form-check-input" %>
                <%= f.label :is_deleted_false, "有効", class: "form-check-label" %>
              </div>
              <div class="form-check form-check-inline col-md-3 offset-md-1 col-5 offset-2">
                <%= f.radio_button :is_deleted, :true, class: "form-check-input" %>
                <%= f.label :is_deleted_true, "退会", class: "form-check-label" %>
              </div>
            </div>
          </div>
          <div class="row d-flex justify-content-center mt-5">
            <%= f.submit "変更を保存する", class: "btn btn-success"%>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="responsive-title text-center">ユーザー一覧</h1>
      <table class="table text-center mt-5">
        <thead>
          <tr>
            <th>ユーザーID</th>
            <th>ユーザーネーム</th>
            <th>メールアドレス</th>
            <th></th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.name, admin_user_path(user) %></td>
            <td><%= user.email  %></td>
            <td><%= link_to "投稿一覧", admin_user_posts_path(user) %></td>
            <% if user.is_deleted %>
              <td class="text-danger">退会</td>
            <% else %>
              <td class="text-success">有効</td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center mt-5"><%= paginate @users %></div>
    </div>
  </div>
</div>

app/views/admin/users/posts.html.erb
<div class="container">
  <div class="row">
    <h1 class="responsive-title text-center mx-auto mb-5"><%= @user.name %>さんの投稿</h1>
  </div>
  <div class="row">
    <div class="col-12 flex">
      <% if @posts.exists? %>
        <% @posts.each do |post| %>
          <div class="card mb-3 ml-2" style="width: 22rem; height: 30rem;">
            <div class="card-body">
              <%= image_tag post.user.get_profile_image, class: "rounded-circle mr-5 post-profile-image", size: "60x60"%>
              <i class="fas fa-user"></i> <%= post.user.name %>
            </div>
            <div class="swiper post-image mt-3">
              <div class="swiper-wrapper">
                <% post.post_images.each do |image| %>
                  <div class="swiper-slide">
                    <%= link_to admin_post_path(post) do %>
                      <%= image_tag image, style: "height: 35em" %>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <!-- ページネーションの要素 -->
              <div class="swiper-pagination"></div>
              <!-- ナビゲーションボタン （前、次） -->
              <div class="swiper-button-prev"><i class="fas fa-chevron-circle-left mr-3"></i></div>
              <div class="swiper-button-next"><i class="fas fa-chevron-circle-right ml-3"></i></div>
            </div>
            <div class="card-body">
              <div class="d-flex border-bottom">
                <!--投稿時間表示-->
                <div class="ml-auto mr-2"><%= "#{time_ago_in_words(post.created_at)}前" %></div>
              </div>
              <!--タグ付け-->
              <% post.tags.limit(3).each do |tag| %>
                <i class="fas fa-tag"></i><strong><%= tag.name %></strong>
              <% end %>
              <% if post.tags.count > 3 %>
                ...
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <h3 class="mx-auto text-center mt-5">投稿はありません</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-12">
      <h1 class="responsive-title text-center"><%= @user.name %>さんのユーザー情報</h1>
      <div class="row my-5 justify-content-center">
        <span class="col-sm-3 text-center mb-3 mb-md-0">プロフィール画像</span>
        <span class="col-sm-9 text-center text-md-left"><%= image_tag @user.get_profile_image, class: "rounded-circle", size: "180x180" %></span>
      </div>
      <div class="row mb-5">
        <span class="col-sm-3 text-center mb-3 mb-md-0">ユーザーネーム</span>
        <span class="col-sm-9 text-center text-md-left"><%= @user.name %></span>
      </div>
      <div class="row mb-5 mx-auto">
        <span class="col-sm-3 text-center mb-3 mb-md-0">自己紹介</span>
        <span class="col-sm-9 col-12 border rounded bg-light mx-auto py-1"><%= simple_format(@user.introduction) %></span>
      </div>
      <div class="row mb-5">
        <span class="col-sm-3 text-center mb-3 mb-md-0">ステータス</span>
        <span class="col-sm-9 text-center text-md-left">
          <% if @user.is_deleted %>
            <div class="text-danger">退会</div>
          <% else %>
            <div class="text-success">有効</div>
          <% end %>
        </span>
      </div>
      <div class="d-flex justify-content-center">
        <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success col-6" %>
      </div>
    </div>
  </div>
</div>