config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用のパス
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :edit, :update] do
      # ユーザーの投稿一覧ページのルーティング
      get 'posts'
    end
    resources :tags, except: [:new, :show]
    resources :posts, only: [:show, :destroy]
    resources :reports, only: [:index, :show, :update, :destroy]
  end

   scope module: :public do
    root to:  'homes#top'
    # 退会確認画面のルーティング
    get  '/users/check' => 'users#check'
    # 論理削除のルーティング
    patch  '/users/withdraw' => 'users#withdraw'
    # 通知機能のルーティング
    resources :notifications, only: [:index, :destroy]
    # 通報完了画面のルーティング
    get 'reports/completed' => 'reports#completed', as: 'completed'
    resources :posts do
      collection do
      # タグ検索のルーティング
      get 'search_tag'
      get 'search'
      end
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :users, except: [:new, :destroy] do
      member do
        # いいねした投稿を取得するため投稿idを付与
        get :likes
        # 下書き一覧ページのルーティング
        get :draft
      end
      # ユーザーを通報するためのルーティング
      resources :reports, only: [:new, :create]
      resource :relationships, only: [:create, :destroy]
      # フォローしてるユーザーを取得するためのルーティング
      get 'followings' => 'relationships#followings', as: 'followings'
      # フォロワーを取得するためのルーティング
    	get 'followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_tags,dependent: :destroy
  has_many :tags,through: :post_tags, dependent: :destroy
  has_one :notification, as: :subject, dependent: :destroy
  has_many_attached :post_images

  validates :post_images, presence: true
  validates :shop_name, presence: true
  validates :dish_name, presence: true
  validates :caption, length: { maximum: 200 }
  validates :price, presence: true
  validates :address, presence: true
  validate :validate_number_of_files

  # 地図機能
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # 投稿にいいねされてるかの判別
  def liked?(user)
     likes.where(user_id: user.id).exists?
  end

  def save_tag(sent_tags)
    sent_tags.uniq!
    # タグが存在していれば、タグの名前を全て取得
    current_tags = self.tags.pluck(:name)
    # 現在取得したタグから送られてきたタグを除いてold_tagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnew_tagsとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      tag = Tag.find_by(name: old)
      self.post_tags.find_by!(tag_id: tag.id).destroy if tag.present?
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
  end

  # キーワード検索メソッド
  def self.search(search)
    if search != nil && search != ''
      Post.joins(:tags).joins(:user).where('shop_name LIKE(?) OR dish_name LIKE(?) OR caption LIKE(?) OR address LIKE(?) OR tags.name LIKE(?) OR users.name LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%").distinct
    else
      Post.all
    end
  end

  # 最小価格〜最大価格の検索メソッド
  def self.price_search(min_search, max_search)
    if max_search != '' && max_search != nil && min_search != '' && min_search != nil
        @posts = Post.where("price >= #{min_search} and price <= #{max_search}")
    elsif max_search != '' && max_search != nil
        @posts = Post.where("price <= #{max_search}")
    elsif min_search != '' && min_search != nil
        @posts = Post.where("price >= #{min_search}")
    end
  end

  # 添付できる画像を４枚までに制限
  FILE_NUMBER_LIMIT = 4
  def validate_number_of_files
    return if post_images.length <= FILE_NUMBER_LIMIT
    errors.add(:post_images, "の添付は#{FILE_NUMBER_LIMIT}枚までです。")
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul style="list-style: none;">
      <% obj.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<% if request.fullpath.include? "/admin" %>
  <% if admin_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        <div id="top">
          <a href="#"><%= image_tag asset_path("Foodium.jpg"), class: "navbar-brand", size: "90x80" %></a>
        </div>
        <!--ハンバーガーメニュー-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item search-group">
              <%= link_to "#", class: "nav-link active btn1" do %>
                <i class="fas fa-search rounded-circle p-2 bg-light"></i> 検索
              <% end %>
              <!--ユーザー検索フォーム-->
              <div class="search-form mt-2", style='display:none;'>
                <%= form_with url: admin_users_path, local: true, method: :get, class: "input-group" do |f| %>
                  <%= f.text_field :word, class: "form-control", placeholder: "ユーザー検索" %>
                  <%= button_tag type: "submit", class: " form-control btn btn-light col-3 ml-auto" do %>
          	         <i class="fas fa-search"></i>
                  <% end %>
                <% end %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to admin_users_path, class: "nav-link active" do %>
              <i class="fas fa-users rounded-circle p-2 bg-light"></i> ユーザー一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_tags_path, class: "nav-link active" do %>
                <i class="fas fa-tags rounded-circle p-2 bg-light"></i> タグ一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_reports_path, class: "nav-link active" do %>
                <!--未読の通知がある場合とない場合で分岐-->
                <% if Report.all.where(status: :waiting).exists? %>
                  <i class="fa-sharp fa-solid fa-bell fa-beat rounded-circle p-2 bg-dark" style="color: #f2ee7d;"></i>
                <% else %>
                  <i class="fa-sharp fa-solid fa-bell rounded-circle p-2 bg-light"></i>
                <% end %>
                通報一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link active" do %>
              <i class="fas fa-sign-out-alt rounded-circle p-2 bg-light"></i> ログアウト
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
<% elsif user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <div id="top">
        <a href="#"><%= image_tag asset_path("Foodium.jpg"), class: "navbar-brand", size: "90x80" %></a>
      </div>
      <!--ハンバーガーメニュー-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto ">
          <li class="nav-item">
            <%= link_to posts_path, class: "nav-link active" do %>
              <i class="fas fa-home rounded-circle p-2 bg-light"></i> ホーム
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#", id:"search", class: "nav-link active" do %>
              <i class="fas fa-search rounded-circle p-2 bg-light"></i> 検索
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link active" do %>
              <!--未読の通知がある場合とない場合で分岐-->
              <% if current_user.notifications.where(checked: false).exists? %>
                <i class="fa-sharp fa-solid fa-bell fa-beat rounded-circle p-2 bg-dark" style="color: #f2ee7d;"></i>
              <% else %>
                <i class="fa-sharp fa-solid fa-bell rounded-circle p-2 bg-light"></i>
              <% end %>
              通知
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: "nav-link active" do %>
            <i class="far fa-image rounded-circle p-2 bg-light"></i> 投稿
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user), class: "nav-link active" do %>
            <i class="fas fa-user rounded-circle p-2 bg-light"></i> プロフィール
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link active" do %>
            <i class="fas fa-sign-out-alt rounded-circle p-2 bg-light"></i> ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <script src="https://kit.fontawesome.com/f9e80abfb4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="full-page">
    <header><%= render "layouts/header" %></header>
    <% if user_signed_in? or admin_signed_in? %>
      <span class="ml-1" style="position:relative; top: 96px;"><%= notice %></span>
    <% end %>
    <main>
      <!--ここから検索フォーム-->
      <div id="search-wrap">
         <div class="close-btn"><span></span><span></span></div>
         <div class="search-area ">
            <!--ユーザー検索フォーム-->
            <%= form_with url: users_path, local: true, method: :get do |form| %>
              <div class="input-group">
                <%= form.text_field :word, placeholder: "ユーザー検索(ユーザーネーム)", class: "form-control w-75" %>
                <%= button_tag type: "submit", class: "btn btn-light form-control" do %>
                  <i class="fas fa-search"></i>
                <% end %>
              </div>
            <% end %>
            <div class="border border-dark mt-3"></div>
            <!--投稿検索フォーム-->
            <%= form_with url: search_posts_path, local: true, method: :get do |f| %>
              <%= f.text_field :word, placeholder: "投稿検索(フリーワード: ハンバーグ, 東京...)", class: "form-control w-100 mb-4" %>
              <!--価格検索フォーム-->
              <%= f.number_field :min_search, placeholder: "最小価格(半角入力)", class: "form-control w-100" %> <span class="text-white">〜</span>
              <%= f.number_field :max_search, placeholder: "最大価格(半角入力)", class: "form-control w-100" %>
              <!--タグ検索フォーム-->
            <div class="text-white mt-2">タグ一覧</div>
              <div class="d-flex flex-row flex-wrap p-2 border rounded">
                <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |b| %>
            	    <div class="mx-1">
            	      <%= b.check_box %>
            	      <%= b.label class: "text-white" %>
            	    </div>
                <% end %>
              </div>
              <%= f.submit "絞り込み", class: "btn btn-light d-flex mx-auto mt-3" %>
            <% end %>
          </div>
        </div>
        <!--ここまで検索フォーム-->
        <%= yield %>
      </main>
  </body>
</html>